### ISSUE TITLE
Script reached FAILWITH instruction

### ISSUE THREAD

**Issue by atticlab** [baking-bad/bakers-registry-cli#2]
58:                  SENDER ;
  59:                  ASSERT_CMPEQ ;
  60:                  DUP 3 ;
  61:                  { CDR ; CDR ; CAR %signup_fee } ;
  62:                  AMOUNT ;
  63:                  ASSERT_CMPEQ }
  64:                { { CAR ; CDR %reporterAccount } ;
  65:                  IF_NONE { PUSH bool False } { SENDER ; COMPARE ; EQ } ;
  66:                  DIP { DUP ; IMPLICIT_ACCOUNT ; ADDRESS ; SENDER ; COMPARE ; EQ } ;
  67:                  OR ;
  68:                  ASSERT ;
  69:                  DUP 3 ;
  70:                  { CDR ; CDR ; CDR %update_fee } ;
  71:                  AMOUNT ;
  72:                  ASSERT_CMPEQ } ;
  73:              DIP { NOW ; SWAP ; PAIR ; SOME ; DIP { UNPAIR } } ;
  74:              UPDATE ;
  75:              PAIR ;
  76:              NIL operation ;
  77:              PAIR }
  78:            { DUP 2 ;
  79:              { CDR ; CAR %owner } ;
  80:              SENDER ;
  81:              ASSERT_CMPEQ ;
  82:              AMOUNT ;
  83:              PUSH mutez 0 ;
  84:              ASSERT_CMPEQ ;
  85:              IF_LEFT
  86:                { SWAP ; SET_CDDR ; NIL operation ; PAIR }
  87:                { BALANCE ; UNIT ; TRANSFER_TOKENS ; NIL operation ; SWAP ; CONS ; PAIR } } } }
At line 72 characters 17 to 29,
script reached FAILWITH instruction
with Unit
Fatal error:
  transfer simulation failed
$ ./tezos-client transfer 1.5 from tz1MXFrtZoaXckE41bjUCSjAjAap3AFDSr3N to KT1ChNsEFxwyCbJyWGSL3KdjeXE28AY1Kaog --arg 'Left (Pair "tz1MXFrtZoaXckE41bjUCSjAjAap3AFDSr3N" (Pair (Some (Pair (Pair (Pair 0x457665727374616b65 True) 0x68747470733a2f2f657665727374616b652e6f6e652f74657a6f73) (Pair (Pair 9000 {}) (Pair (Pair (Pair 100000 True) (Pair 6 (Pair 1 10))) (Pair (Pair True 16383) (Pair 100 True)))))) None))' --burn-cap 1 --dry-run

**Comment by m-kus** [comment]
I guess that's because update fee is 0.5
Check out the latest CLI version `pip install -U bakers-registry` - it should return a correct result

**Comment by m-kus** [comment]
Seems you've done it :)
